export const apiUrl = 'http://localhost:5000/api'

export const LOCAL_STORAGE_TOKEN_NAME = 'smart-library'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const CATEGORIES_LOADED_SUCCESS = 'CATEGORIES_LOADED_SUCCESS'
export const CATEGORIES_LOADED_FAIL = 'CATEGORIES_LOADED_FAIL'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const ALL_CATEGORY = 'ALL_CATEGORY'

export const ADD_USER = 'ADD_USER'
export const USERS_LOADED_SUCCESS = 'USERS_LOADED_SUCCESS'
export const USERS_LOADED_FAIL = 'USERS_LOADED_FAIL'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const FIND_USER = 'FIND_USER'

export const ADD_BOOK = 'ADD_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const FIND_BOOK = 'FIND_BOOK'
export const UPDATE_BOOK = 'UPDATE_BOOK'
export const BOOKS_LOADED_SUCCESS = 'BOOKS_LOADED_SUCCESS'
export const BOOKS_LOADED_FAIL = 'BOOKS_LOADED_FAIL'
export const ALL_BOOK = 'ALL_BOOK'

export const ADD_REQUEST = 'ADD_REQUEST'
export const DELETE_REQUEST = 'DELETE_REQUEST'
export const FIND_REQUEST = 'FIND_REQUEST'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const REQUESTS_BORROW_LOADED_SUCCESS = 'REQUESTS_BORROW_LOADED_SUCCESS'
export const REQUESTS_BORROW_LOADED_FAIL = 'REQUESTS_BORROW_LOADED_FAIL'

export const PAGY_PAGE_SIZE = 10;
export const HOME_PAGY_PAGE_SIZE = 12;
